config/routes.rb
ContactForm::Application.routes.draw do

  resources :contacts

end

app/models/contact.rb
class Contact<ActiveRecord::Base
  validates_presence_of :email
  validates_presence_of :subject
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :description

  def self.find_contact(last_name)
    where(last_name:last_name).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController<ApplicationController
  before_action :set_contact, only: [:destroy, :show, :edit, :update]


  def new
    @contact = Contact.new
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact
    else
      render 'edit'
    end
  end

  def edit

  end

  def show

  end

  def index
    @contacts = Contact.all
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to(@contact, notice: 'Contact was successfully created!')
    else
      render 'new'
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:email, :subject, :description, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
    </p>
    <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
    </p>
    <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    </p>
    <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
    </p>
    <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1> Contacts </h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <% @contacts.each do |contact| %>
    <tr>
       <td><%= contact.subject %></td>
       <td><%= contact.first_name %></td>
       <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
       <td><%= link_to 'Show', contact %></td>
       <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
       <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %> <br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
    </p>
    <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
    </p>
    <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    </p>
    <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
    </p>
    <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
  <br>
</p>
<p>
  <strong>Description:</strong>
  <%= @contact.description %>
</p>
<p>
  <strong>Name:</strong>
  <%= "#{@contact.first_name} #{@contact.last_name}" %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>



<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>